#
# Site Settings for Online CV Theme
# Be aware that even a small syntax error here can lead to failures in output
#

# Site configuration
title: Burak Kalafat - CV
description: Professional CV/Resume of Burak Kalafat - Senior Software Engineer (Backend, .NET) specializing in .NET and backend development
baseurl: "/cv" # the subpath of your site, e.g. /blog
url: "https://bkalafat.github.io" # the base hostname & protocol for your site

# Theme configuration
# Available skins: blue, turquoise, green, berry, orange, ceramic
# Choose the one that looks most professional
theme_skin: blue

# SEO and Meta
lang: en
# Google Analytics tracking ID (optional)
# analytics: UA-XXXXXXXXX-X

# Chrome mobile color (optional)
chrome_mobile_color: #42A8C0

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - PLAN.md
  - BURAK_KALAFAT.pdf
  - BURAK_KALAFAT.docx
  - _config.yml.backup
  - output/
  - downloads/
  - "*.gem"
  - "*.gemspec"
  - LICENSE
  - package.json
  - package-lock.json
  - .github/
  - docker-compose.yml

# Google Analytics (optional)
# google_analytics: "UA-XXXXXXX-X"

# Additional settings for modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed
