name: Build and Deploy CV

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Generate PDF
  generate-pdf:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
          
      - name: Build Jekyll site
        run: bundle exec jekyll build
        
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          
      - name: Check generated files
        run: |
          echo "Checking _site directory structure:"
          ls -la _site/
          echo "Looking for print directory:"
          find _site -type d -name "print"
          echo "Looking for all HTML files:"
          find _site -name "*.html" -type f | head -20
          
      - name: Generate PDF from HTML (using print layout)
        run: |
          mkdir -p output
          # Try to find the print index.html file
          if [ -f "_site/print/index.html" ]; then
            HTML_FILE="_site/print/index.html"
          elif [ -f "_site/cv/print/index.html" ]; then
            HTML_FILE="_site/cv/print/index.html"
          else
            echo "Error: Cannot find print/index.html"
            exit 1
          fi
          echo "Using HTML file: $HTML_FILE"
          wkhtmltopdf --enable-local-file-access --print-media-type "file://$PWD/$HTML_FILE" output/Burak_Kalafat_CV.pdf
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: output/Burak_Kalafat_CV.pdf
          retention-days: 90
          
      - name: Commit PDF to repository
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mkdir -p downloads
          cp output/Burak_Kalafat_CV.pdf downloads/
          git add downloads/ || true
          git commit -m "Update generated PDF [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
