name: Generate DOCX Resume

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      - name: Create Markdown Resume
        run: |
          cat > resume.md << 'EOF'
          ---
          title: "Burak Kalafat - CV"
          author: "Burak Kalafat"
          ---
          
          # BURAK KALAFAT
          ## Senior Software Engineer (Backend, .NET)
          
          **Email:** burakkalafat89@gmail.com  
          **Phone:** +905403506161  
          **GitHub:** https://github.com/bkalafat  
          **LinkedIn:** https://www.linkedin.com/in/bkalafat/
          
          ---
          
          ## Career Profile
          
          **Senior Software Engineer (Backend, .NET)** with 12+ years of experience specializing in large-scale legacy modernization, clean architecture, and high-performance backend systems within the financial sector. Proven technical leader adept at mentoring teams, conducting code reviews, and driving architectural decisions.
          
          **GitHub Copilot Enterprise champion** with specialized expertise in AI-assisted development, delivering organization-wide training and achieving **6-8× acceleration** on a **60,000-line COBOL-to-microservices migration** within 3 months. Expert in Spec-Driven Development (SDD) and prompt engineering for enterprise-scale modernization.
          
          Demonstrated impact through **performance optimization** (5-6× concurrent user capacity increase), **technical leadership** (code review ownership, team mentorship), and **architectural excellence** (Clean Architecture, design patterns, asynchronous programming).
          
          ---
          
          ## Work Experience
          
          ### Expert .NET Developer | Innovance (Remote)
          **May 2024 - Present** | Istanbul
          
          Lead technical modernization initiatives across major financial institutions, serving as technical advisor and GitHub Copilot champion:
          
          **Akbank - Merchant Payment System Modernization**:
          - Modernized **60,000 lines** of legacy COBOL mainframe code to modern C# and Java microservices in **3 months**, achieving **6-8× acceleration** through AI-assisted development
          - Provided technical leadership through architectural guidance, coding standards establishment, and team mentorship on Clean Architecture principles
          - Delivered **3 company-wide presentations** on GitHub Copilot Enterprise adoption to management, establishing AI-assisted development best practices organization-wide
          - Implemented Spec-Driven Development (SDD) methodology using GitHub Copilot Ask/Edit modes, eliminating hallucinations and ensuring zero scope drift
          - Applied Repository, Unit of Work, Facade, and Strategy design patterns to ensure maintainable, testable codebase
          
          **Turkiye Finans - Internet and Mobile Banking Backend**:
          - Developed robust banking backend systems using MVC, WCF, and MSSQL with comprehensive unit testing coverage
          
          *Technologies: C#, .NET Core, Java, MVC, WCF, MSSQL, GitHub Copilot Enterprise, Prompt Engineering, Design Patterns, GitHub Actions, Azure DevOps*
          
          ---
          
          ### Senior .NET Developer | InsightSoftware (Remote)
          **September 2022 - April 2024** | North Carolina
          
          - Contributed to architecture, design, and implementation of backend-focused features using C#
          - Collaborated within an international, remote-first environment
          - Delivered scalable, maintainable solutions
          
          *Technologies: C#, .NET Core, Backend Architecture*
          
          ---
          
          ### Senior .NET Developer | OBSS
          **September 2017 - September 2022** | Istanbul
          
          Led technical modernization and architecture initiatives across major Turkish banks with code review responsibilities and team mentorship:
          
          **Halkbank - Mobile Banking Backend Transformation**:
          - Architected and led migration from legacy .NET Framework to Clean Architecture using .NET Core microservices
          - Increased concurrent user capacity **5-6× per server** through asynchronous programming patterns and thread optimization strategies
          - Developed scalable REST APIs with EF Core and MSSQL, deployed via Azure DevOps CI/CD pipelines
          - Implemented Repository and Unit of Work patterns for maintainable data access layer
          
          **Turkiye Finans - Technical Leadership and Code Review**:
          - Owned code review process for development team, ensuring code quality, best practices, and architectural compliance
          - Mentored development team through regular code reviews and architectural guidance sessions
          - Developed enterprise-level corporate customer solutions using WinForms and WCF services
          - Established coding standards and review guidelines, improving code quality and reducing bug rates
          
          **Akbank - Payment System Full-Stack Development**:
          - Led Payment System campaign as Full-Stack Developer using TypeScript, Knockout.js, C#, and Java Spring
          - Integrated frontend and backend systems with Oracle 12c database, ensuring transactional consistency
          
          *Technologies: .NET Core, REST APIs, EF Core, MSSQL, Clean Architecture, Asynchronous Programming, TypeScript, Knockout.js, Java Spring, Oracle 12c, Azure DevOps, Design Patterns*
          
          ---
          
          ### Java Developer | TUBITAK
          **January 2017 - September 2017** | Kocaeli
          
          - Utilized Java and APDU protocols to write high-level security EAC SAC data to smartcard passport chips
          - Contributed to secure government identification systems
          
          *Technologies: Java, APDU, Smartcard Technology*
          
          ---
          
          ### .NET Developer | VakıfBank
          **August 2013 - February 2017** | Istanbul
          
          - Transformed legacy systems to service-oriented architectures for CRM and Collections teams
          - Implemented MVVM pattern with WPF and WCF services
          - Developed database solutions using Oracle 11g and PL/SQL
          
          *Technologies: .NET, MVVM, WPF, WCF, Oracle 11g, PL/SQL*
          
          ---
          
          ### Part-Time .NET Developer | VeriPark
          **December 2012 - June 2013** | Izmir
          
          - Developed custom widgets using ASP.NET for Turkcell SharePoint environment
          - Contributed part-time while completing university studies
          
          *Technologies: ASP.NET, SharePoint*
          
          ---
          
          ## Education
          
          **BSc in Computer Engineering**  
          Ege University | 2008 - 2013
          
          ---
          
          ## Certifications
          
          - **Introduction to GitHub Copilot** - Microsoft Learn (2024)
          - **Build Microservices with .NET and Amazon Web Services** - Udemy (2024)
          - **React Nanodegree Program** - Udacity (2020)
          
          ---
          
          ## Skills & Proficiency
          
          - **C# and .NET Core Microservices** - Expert
          - **GitHub Copilot Enterprise and AI-Assisted Development** - Expert
          - **Clean Architecture and Design Patterns** - Expert
          - **REST APIs and Asynchronous Programming** - Expert
          - **EF Core and Database Design (MSSQL, Oracle)** - Advanced
          - **Azure DevOps and GitHub Actions CI/CD** - Advanced
          - **Unit Testing and E2E Testing (Playwright)** - Advanced
          - **TypeScript, JavaScript and Java Spring** - Advanced
          - **Technical Leadership and Code Review** - Advanced
          
          ---
          
          ## Languages
          
          - **Turkish** - Native
          - **English** - Professional
          
          ---
          
          ## Interests
          
          Chess, LLM & RAG-based Enterprise Solutions, AI-Powered Customer Service Systems, Travel & Exploring Cultures
          
          ---
          
          *References available upon request*
          EOF
          
      - name: Generate DOCX from Markdown
        run: |
          mkdir -p output
          pandoc resume.md \
            -o output/Burak_Kalafat_CV.docx \
            --from markdown \
            --to docx \
            --standalone \
            --reference-doc=reference.docx 2>/dev/null || \
          pandoc resume.md \
            -o output/Burak_Kalafat_CV.docx \
            --from markdown \
            --to docx \
            --standalone
            
      - name: Upload DOCX artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-docx
          path: output/Burak_Kalafat_CV.docx
          retention-days: 90
          
      - name: Commit generated files (optional)
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull --rebase origin main
          mkdir -p downloads
          cp output/Burak_Kalafat_CV.docx downloads/
          git add downloads/Burak_Kalafat_CV.docx
          git diff --staged --quiet || git commit -m "Auto-update: Generated DOCX CV [skip ci]"
          git push origin main || echo "Push failed, but artifact is uploaded"
